name: build_ErfanGSIs

on:
  watch:
    types: [started]
    
env:
  ROM_URL: https://static-yz-cdn.c-t.work/QN_FOG_56a79866-a4af-4b0a-bb1f-dc64ac8fe0d4%2F9fe819aa-70df-4af9-b036-51fa33d1c768%2FOLX_MiuiCY_raphael_21.11.1_57271d0.zip?t-s=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJndWlkK3RpbWVzdGFtcCI6Imlsb3ZlY293dHJhbnNmZXIyMDIxXzE2MzY4MDczMzg2NzIifQ.yzNo0ceEgflr3JLCvohahiPU8S_ZeEXVrV5K1q-DoyY&t-c=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJndWlkK3RpbWVzdGFtcCI6IjIwMjF8MTF8MTN8MjAifQ.QBOEcIMydrU-LoaCUW6kssYiMe0jPhzfPGyx9mK2qSc&user=56a79866-a4af-4b0a-bb1f-dc64ac8fe0d4&ut=0&rt=0&rk=ff_3b416960-d98b-47b7-89e3-303ad01a1d45&owner=56a79866-a4af-4b0a-bb1f-dc64ac8fe0d4&attname=OLX_MiuiCY_raphael_21.11.1_57271d0.zip

  ROM_NAME: MIUI
  BUILD_AB: true
  BUILD_AONLY: false
  ROM_AONLY: k20pro.7z
  ROM_AB: k20pro.7z

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk p7zip gzip
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
       
       - name: Use Xiaoxin SGSI build tool Script
         run: |
              sudo rm -rf $GITHUB_WORKSPACE/ErfanGSIs/setup.sh
              sudo cp -r setup.sh $GITHUB_WORKSPACE/ErfanGSIs
              sudo chmod 777 -R $GITHUB_WORKSPACE/ErfanGSIs
              cd ErfanGSIs
              mkdir ./output
              sudo bash setup.sh
       
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
           
       - name: Clear output
         if: env.BUILD_AB == 'true'
         run: sudo rm -rf ErfanGSIs/output/*
         
       - name: Download Stock Rom & Generate AB GSI
         if: env.BUILD_AB == 'true'
         run: sudo ./ErfanGSIs/url2GSI.sh -b $ROM_URL $ROM_NAME

       - name: 7z AB GSI
         if: env.BUILD_AB == 'true'
         run: 7za a -t7z -r $ROM_AB ErfanGSIs/output/*

       - name: Upload AB GSI to WeTransfer
         if: env.BUILD_AB == 'true'
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet $ROM_AB
         
            
